# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Instalamos el CLI de Angular globalmente
RUN npm install -g @angular/cli@18

# Copiamos archivos de dependencias
COPY package*.json ./
RUN npm install

COPY . .

# Exponemos el puerto de Angular
EXPOSE 4200

# Comando para levantar el servidor de desarrollo con acceso externo
CMD ["ng", "serve", "--host", "0.0.0.0"]