version: '3.8'

services:
  # Base de Datos con extensiones espaciales (SMIA)
  db:
    image: postgis/postgis:15-3.3
    container_name: smia_db
    environment:
      POSTGRES_DB: smia_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Django
  backend:
    build: ./backend
    container_name: smia_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:adminpassword@db:5432/smia_db

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: smia_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: