# Generated by Django 6.0.4 on 2026-04-27 03:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estacion', models.CharField(choices=[('PASIVA', 'Estación Pasiva'), ('AUTOMATICA', 'Estación Automática'), ('ACTIVA', 'Estación Activa')], default='AUTOMATICA', max_length=20)),
                ('codigo_monica', models.CharField(help_text='Código oficial Red MoniCA', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Estación de Aire',
                'verbose_name_plural': 'Estaciones de Aire',
                'db_table': 'smia_estaciones_aire',
            },
        ),
        migrations.CreateModel(
            name='PuntoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuerpo', models.CharField(choices=[('RIO', 'Río'), ('LAGUNA', 'Laguna'), ('CANAL', 'Canal')], max_length=20)),
                ('cuenca', models.CharField(help_text='Ej: Cuenca del Río Choqueyapu', max_length=100)),
            ],
            options={
                'verbose_name': 'Punto de Agua',
                'verbose_name_plural': 'Puntos de Agua',
                'db_table': 'smia_puntos_agua',
            },
        ),
        migrations.CreateModel(
            name='MuestraAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('pm25', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='PM2.5 (µg/m³)')),
                ('pm10', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='PM10 (µg/m³)')),
                ('no2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='NO₂ (µg/m³)')),
                ('so2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='SO₂ (µg/m³)')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='CO (ppm)')),
                ('o3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='O₃ (µg/m³)')),
                ('ica_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='ICA (4 decimales)')),
                ('ica_nivel', models.CharField(blank=True, choices=[('BUENO', 'Bueno (0-50)'), ('MODERADO', 'Moderado (51-100)'), ('SENSIBLE', 'Dañino grupos sensibles (101-150)'), ('DANINO', 'Dañino (151-200)'), ('MUY_DAN', 'Muy dañino (201+)')], max_length=10)),
                ('ica_contaminante_critico', models.CharField(blank=True, help_text='Contaminante que determinó el ICA', max_length=10)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='monitoreo.estacionaire')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Muestra de Aire',
                'verbose_name_plural': 'Muestras de Aire',
                'db_table': 'smia_muestras_aire',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MuestraAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH')),
                ('dbo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DBO₅ (mg/L)')),
                ('dqo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DQO (mg/L)')),
                ('coliformes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coliformes fecales (UFC/100ml)')),
                ('turbidez', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Turbidez (NTU)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('cumple_ley', models.BooleanField(null=True, verbose_name='Cumple Ley N°1333')),
                ('parametros_excedidos', models.JSONField(default=list, verbose_name='Parámetros que exceden límites')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('punto_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='monitoreo.puntoagua')),
            ],
            options={
                'verbose_name': 'Muestra de Agua',
                'verbose_name_plural': 'Muestras de Agua',
                'db_table': 'smia_muestras_agua',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PuntoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('AIRE', 'Calidad del Aire'), ('AGUA', 'Calidad del Agua'), ('RESIDUOS', 'Gestión de Residuos'), ('RUIDO', 'Contaminación Acústica'), ('VEHICULAR', 'Emisiones Vehiculares')], max_length=20)),
                ('latitud', models.DecimalField(decimal_places=7, help_text='Latitud WGS84. Ej: -16.5000', max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, help_text='Longitud WGS84. Ej: -68.1500', max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Monitoreo',
                'verbose_name_plural': 'Puntos de Monitoreo',
                'db_table': 'smia_puntos_monitoreo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='puntoagua',
            name='punto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punto_agua', to='monitoreo.puntomonitoreo'),
        ),
        migrations.CreateModel(
            name='MedicionVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('placa', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('anio_vehiculo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año del vehículo')),
                ('co_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='CO (%)')),
                ('hc_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HC (ppm)')),
                ('nox_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='NOx (ppm)')),
                ('opacidad_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Opacidad (%)')),
                ('cumple_norma', models.BooleanField(verbose_name='Cumple norma')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_vehiculares', to='monitoreo.puntomonitoreo')),
            ],
            options={
                'verbose_name': 'Medición Vehicular',
                'verbose_name_plural': 'Mediciones Vehiculares',
                'db_table': 'smia_mediciones_vehiculares',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MedicionRuido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('zona', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], max_length=20)),
                ('nivel_db', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Nivel de ruido (dB)')),
                ('es_nocturno', models.BooleanField(default=False, help_text='True si la medición es horario nocturno')),
                ('es_excedencia', models.BooleanField(default=False, verbose_name='Excede límite reglamentario')),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_ruido', to='monitoreo.puntomonitoreo')),
            ],
            options={
                'verbose_name': 'Medición de Ruido',
                'verbose_name_plural': 'Mediciones de Ruido',
                'db_table': 'smia_mediciones_ruido',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='estacionaire',
            name='punto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estacion_aire', to='monitoreo.puntomonitoreo'),
        ),
        migrations.CreateModel(
            name='PuntoResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_punto', models.CharField(choices=[('RELLENO', 'Relleno Sanitario'), ('P_VERDE', 'Punto Verde'), ('TRANSFER', 'Estación de Transferencia')], max_length=20)),
                ('capacidad_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad (toneladas/día)')),
                ('operador', models.CharField(blank=True, max_length=200)),
                ('punto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punto_residuos', to='monitoreo.puntomonitoreo')),
            ],
            options={
                'verbose_name': 'Punto de Residuos',
                'verbose_name_plural': 'Puntos de Residuos',
                'db_table': 'smia_puntos_residuos',
            },
        ),
        migrations.CreateModel(
            name='PesajeResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_residuo', models.CharField(choices=[('ORGANICO', 'Orgánico'), ('RECICLABLE', 'Reciclable'), ('ESPECIAL', 'Especial'), ('MIXTO', 'Mixto')], max_length=20)),
                ('peso_toneladas', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso (toneladas)')),
                ('operador', models.CharField(max_length=200)),
                ('sigir_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('SINCRONIZADO', 'Sincronizado con SIGIR'), ('ERROR', 'Error de sincronización')], default='PENDIENTE', max_length=20)),
                ('sigir_timestamp', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('punto_residuos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='monitoreo.puntoresiduos')),
            ],
            options={
                'verbose_name': 'Pesaje de Residuos',
                'verbose_name_plural': 'Pesajes de Residuos',
                'db_table': 'smia_pesajes_residuos',
                'ordering': ['-fecha'],
            },
        ),
    ]
