# Generated by Django 6.0.4 on 2026-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Contaminación Aire', 'Contaminación del aire / Emisiones'), ('Contaminación Ríos', 'Contaminación de ríos'), ('Tala Ilegal', 'Tala ilegal de árboles'), ('Basura', 'Acumulación de basura / Residuos'), ('Ruido', 'Ruido excesivo comercial'), ('Otro', 'Otro problema ambiental')], max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_seguimiento', models.CharField(editable=False, max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
