# Generated by Django 6.0.4 on 2026-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSMIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('DIRECTOR', 'Director SMGA'), ('TECNICO_AIRE', 'Técnico Calidad del Aire'), ('TECNICO_AGUA', 'Técnico Calidad del Agua'), ('TECNICO_RES', 'Técnico Gestión de Residuos'), ('TECNICO_RUIDO', 'Técnico Control de Ruido'), ('TECNICO_VEH', 'Técnico Emisiones Vehiculares'), ('AUDITOR', 'Auditor ASDI/Helvetas'), ('CIUDADANO', 'Ciudadano La Paz')], default='CIUDADANO', max_length=20)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'smia_usuarios',
            },
        ),
    ]
